# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetColorPanel(object):
    def setupUi(self, SetColorPanel):
        SetColorPanel.setObjectName("SetColorPanel")
        SetColorPanel.resize(281, 206)
        self.SaveColor = QtWidgets.QPushButton(SetColorPanel)
        self.SaveColor.setGeometry(QtCore.QRect(10, 40, 121, 41))
        self.SaveColor.setObjectName("SaveColor")
        self.GreenButton = QtWidgets.QPushButton(SetColorPanel)
        self.GreenButton.setGeometry(QtCore.QRect(10, 100, 121, 41))
        self.GreenButton.setObjectName("GreenButton")
        self.RedButton = QtWidgets.QPushButton(SetColorPanel)
        self.RedButton.setGeometry(QtCore.QRect(150, 40, 121, 41))
        self.RedButton.setObjectName("RedButton")
        self.BlackButton = QtWidgets.QPushButton(SetColorPanel)
        self.BlackButton.setGeometry(QtCore.QRect(150, 100, 121, 41))
        self.BlackButton.setObjectName("BlackButton")
        self.label = QtWidgets.QLabel(SetColorPanel)
        self.label.setGeometry(QtCore.QRect(100, 10, 91, 16))
        self.label.setObjectName("label")
        self.ReturnButton = QtWidgets.QPushButton(SetColorPanel)
        self.ReturnButton.setGeometry(QtCore.QRect(100, 160, 71, 31))
        self.ReturnButton.setObjectName("ReturnButton")

        self.retranslateUi(SetColorPanel)
        QtCore.QMetaObject.connectSlotsByName(SetColorPanel)

    def retranslateUi(self, SetColorPanel):
        _translate = QtCore.QCoreApplication.translate
        SetColorPanel.setWindowTitle(_translate("SetColorPanel", "Dialog"))
        self.SaveColor.setText(_translate("SetColorPanel", "Стандартная"))
        self.GreenButton.setText(_translate("SetColorPanel", "Зеленая"))
        self.RedButton.setText(_translate("SetColorPanel", "Красная"))
        self.BlackButton.setText(_translate("SetColorPanel", "Темная"))
        self.label.setText(_translate("SetColorPanel", "Цвета формы"))
        self.ReturnButton.setText(_translate("SetColorPanel", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SetColorPanel = QtWidgets.QDialog()
    ui = Ui_SetColorPanel()
    ui.setupUi(SetColorPanel)
    SetColorPanel.show()
    sys.exit(app.exec_())
