# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetColorPanel(object):
    def setupUi(self, SetColorPanel):
        SetColorPanel.setObjectName("SetColorPanel")
        SetColorPanel.resize(324, 197)
        self.textEdit = QtWidgets.QTextEdit(SetColorPanel)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 161, 31))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(SetColorPanel)
        self.label.setGeometry(QtCore.QRect(180, 30, 121, 16))
        self.label.setObjectName("label")
        self.textEdit_2 = QtWidgets.QTextEdit(SetColorPanel)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 60, 161, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_2 = QtWidgets.QLabel(SetColorPanel)
        self.label_2.setGeometry(QtCore.QRect(180, 70, 101, 16))
        self.label_2.setObjectName("label_2")
        self.textEdit_3 = QtWidgets.QTextEdit(SetColorPanel)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 100, 161, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_3 = QtWidgets.QLabel(SetColorPanel)
        self.label_3.setGeometry(QtCore.QRect(180, 110, 71, 16))
        self.label_3.setObjectName("label_3")
        self.SaveColor = QtWidgets.QPushButton(SetColorPanel)
        self.SaveColor.setGeometry(QtCore.QRect(30, 140, 121, 41))
        self.SaveColor.setObjectName("SaveColor")

        self.retranslateUi(SetColorPanel)
        QtCore.QMetaObject.connectSlotsByName(SetColorPanel)

    def retranslateUi(self, SetColorPanel):
        _translate = QtCore.QCoreApplication.translate
        SetColorPanel.setWindowTitle(_translate("SetColorPanel", "Dialog"))
        self.label.setText(_translate("SetColorPanel", "Mplayer Form в RGB"))
        self.label_2.setText(_translate("SetColorPanel", "PlayPause в RGB"))
        self.label_3.setText(_translate("SetColorPanel", "Open в RGB"))
        self.SaveColor.setText(_translate("SetColorPanel", "Сохранить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SetColorPanel = QtWidgets.QDialog()
    ui = Ui_SetColorPanel()
    ui.setupUi(SetColorPanel)
    SetColorPanel.show()
    sys.exit(app.exec_())
