# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogForm(object):
    def setupUi(self, Ui_LogForm):
        Ui_LogForm.setObjectName("Ui_LogForm")
        Ui_LogForm.resize(955, 536)
        self.textEdit = QtWidgets.QTextEdit(Ui_LogForm)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 871, 521))
        self.textEdit.setObjectName("textEdit")
        self.returnButton = QtWidgets.QPushButton(Ui_LogForm)
        self.returnButton.setGeometry(QtCore.QRect(890, 10, 61, 511))
        self.returnButton.setObjectName("returnButton")

        self.retranslateUi(Ui_LogForm)
        QtCore.QMetaObject.connectSlotsByName(Ui_LogForm)

    def retranslateUi(self, Ui_LogForm):
        _translate = QtCore.QCoreApplication.translate
        Ui_LogForm.setWindowTitle(_translate("Ui_LogForm", "Dialog"))
        self.returnButton.setText(_translate("Ui_LogForm", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_LogForm = QtWidgets.QDialog()
    ui = Ui_LogForm()
    ui.setupUi(Ui_LogForm)
    Ui_LogForm.show()
    sys.exit(app.exec_())
