# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogToAdmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminForm(object):
    def setupUi(self, Ui_AdminForm):
        Ui_AdminForm.setObjectName("AdminForm")
        Ui_AdminForm.resize(311, 240)
        self.label = QtWidgets.QLabel(Ui_AdminForm)
        self.label.setGeometry(QtCore.QRect(140, 90, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Ui_AdminForm)
        self.label_2.setGeometry(QtCore.QRect(140, 20, 41, 20))
        self.label_2.setObjectName("label_2")
        self.TexBox_LogIN = QtWidgets.QLineEdit(Ui_AdminForm)
        self.TexBox_LogIN.setGeometry(QtCore.QRect(50, 40, 211, 31))
        self.TexBox_LogIN.setObjectName("TexBox_LogIN")
        self.TextBox_Password = QtWidgets.QLineEdit(Ui_AdminForm)
        self.TextBox_Password.setGeometry(QtCore.QRect(50, 110, 211, 31))
        self.TextBox_Password.setObjectName("TextBox_Password")
        self.Button_Log_In = QtWidgets.QPushButton(Ui_AdminForm)
        self.Button_Log_In.setGeometry(QtCore.QRect(50, 150, 93, 41))
        self.Button_Log_In.setObjectName("Button_Log_In")
        self.pushButton = QtWidgets.QPushButton(Ui_AdminForm)
        self.pushButton.setGeometry(QtCore.QRect(170, 150, 93, 41))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Ui_AdminForm)
        QtCore.QMetaObject.connectSlotsByName(Ui_AdminForm)

    def retranslateUi(self, Ui_AdminForm):
        _translate = QtCore.QCoreApplication.translate
        Ui_AdminForm.setWindowTitle(_translate("Ui_AdminForm", "Dialog"))
        self.label.setText(_translate("Ui_AdminForm", "Пароль"))
        self.label_2.setText(_translate("Ui_AdminForm", "Логин"))
        self.Button_Log_In.setText(_translate("Ui_AdminForm", "Войти"))
        self.pushButton.setText(_translate("Ui_AdminForm", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_AdminForm = QtWidgets.QDialog()
    ui = Ui_AdminForm()
    ui.setupUi(Ui_AdminForm)
    Ui_AdminForm.show()
    sys.exit(app.exec_())
